apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrency-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concurrency-control
  template:
    metadata:
      labels:
        app: concurrency-control
    spec:
      serviceAccountName: ci-use
      containers:
      - name: control
        image: quay.io/crc-org/concurrency:v0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"      
            memory: "256Mi"  
          limits:
            cpu: "500m"     
            memory: "512Mi"
        command: ["python3", "-u"]     
        args: ["/opt/control.py"] 
        env:
        - name: SERVER
          value: "https://api.gpc.ocp-hub.prod.psi.redhat.com:6443"
        - name: NAMESPACE
          value: "devtoolsqe--pipeline"
        - name: MACHINE_CM
          value: "machine-status-config"
        - name: LABEL_MACHINE_PR
          value: "tester"
        - name: LAEBL_MACHINE_TASK
          value: "builder"
        - name: LABEL_TASK
          value: "build-installer"
