apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrency-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concurrency-control
  template:
    metadata:
      labels:
        app: concurrency-control
    spec:
      serviceAccountName: ci-use
      initContainers:
      - name: init-log-dir
        image: registry.access.redhat.com/ubi9/ubi-minimal
        command:
          - sh
          - -c
          - |
            mkdir -p /var/log/app && chmod 775 /var/log/app
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/app
      containers:
      - name: control
        image: quay.io/crc-org/concurrency:v0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"      
            memory: "256Mi"  
          limits:
            cpu: "500m"     
            memory: "512Mi"
        command: ["python3", "-u"]     
        args: ["/opt/control.py"] 
        env:
        - name: KUBECONFIG
          value: /kube/config
        - name: SERVER
          value: "https://api.gpc.ocp-hub.prod.psi.redhat.com:6443"
        - name: NAMESPACE
          value: "devtoolsqe--pipeline"
        - name: MACHINE_CM
          value: "machine-status-config"
        - name: LABEL_MACHINE_PR
          value: "tester"
        - name: LAEBL_MACHINE_TASK
          value: "builder"
        - name: LABEL_TASK
          value: "build-installer"
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/app
        - name: kubeconfig
          mountPath: /kube
          readOnly: true
        - name: secret-windows-1-brno
          mountPath: "/opt/secret-windows-1-brno" 
          readOnly: true
        - name: secret-windows-1-blr
          mountPath: "/opt/secret-windows-1-blr" 
          readOnly: true
        - name: secret-mac-1-brno
          mountPath: "/opt/secret-mac-1-brno" 
          readOnly: true
        - name: secret-mac-2-brno
          mountPath: "/opt/secret-mac-2-brno" 
          readOnly: true
        - name: secret-mac-1-blr
          mountPath: "/opt/secret-mac-1-blr" 
          readOnly: true
        - name: secret-mac-3-brno
          mountPath: "/opt/secret-mac-3-brno" 
          readOnly: true
        - name: secret-mac-4-brno
          mountPath: "/opt/secret-mac-4-brno" 
          readOnly: true
        - name: secret-mac-5-brno
          mountPath: "/opt/secret-mac-5-brno" 
          readOnly: true
        - name: secret-mac-6-brno
          mountPath: "/opt/secret-mac-6-brno" 
          readOnly: true
        - name: secret-mac-7-brno
          mountPath: "/opt/secret-mac-7-brno" 
          readOnly: true
        - name: secret-mac-8-brno
          mountPath: "/opt/secret-mac-8-brno" 
          readOnly: true
        - name: secret-mac-9-brno
          mountPath: "/opt/secret-mac-9-brno" 
          readOnly: true
        - name: secret-rhel-1-blr
          mountPath: "/opt/secret-rhel-1-blr" 
          readOnly: true
        - name: secret-rhel-1-brno
          mountPath: "/opt/secret-rhel-1-brno" 
          readOnly: true
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: concurrency-log
      - name: kubeconfig
        configMap:
          name: kubeconfig-with-qps
          items:
          - key: config
            path: config
      - name: secret-windows-1-brno
        secret:
          secretName: secret-windows-1-brno
      - name: secret-windows-1-blr
        secret:
          secretName: secret-windows-1-blr
      - name: secret-mac-1-brno
        secret:
          secretName: secret-mac-1-brno
      - name: secret-mac-2-brno
        secret:
          secretName: secret-mac-2-brno
      - name: secret-mac-1-blr
        secret:
          secretName: secret-mac-1-blr
      - name: secret-mac-3-brno
        secret:
          secretName: secret-mac-3-brno
      - name: secret-mac-4-brno
        secret:
          secretName: secret-mac-4-brno
      - name: secret-mac-5-brno
        secret:
          secretName: secret-mac-5-brno
      - name: secret-mac-6-brno
        secret:
          secretName: secret-mac-6-brno
      - name: secret-mac-7-brno
        secret:
          secretName: secret-mac-7-brno
      - name: secret-mac-8-brno
        secret:
          secretName: secret-mac-8-brno
      - name: secret-mac-9-brno
        secret:
          secretName: secret-mac-9-brno
      - name: secret-rhel-1-blr
        secret:
          secretName: secret-rhel-1-blr
      - name: secret-rhel-1-brno
        secret:
          secretName: secret-rhel-1-brno
