apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig-with-qps
  namespace: devtoolsqe--pipeline
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: in-cluster
      cluster:
        server: https://kubernetes.default.svc
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

    users:
    - name: ci-user
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        client-qps: 30
        client-burst: 60

    contexts:
    - name: default
      context:
        cluster: in-cluster
        user: ci-user

    current-context: default
